// src/components/Navbar.vue
<template>
    <header class="fixed md:flex md:items-center">
      <div class="flex items-center py-3 sm:p-0">
        <div class="pt-4 px-4 pb-4">
          <button @click="isOpen = !isOpen" type="button" class="block text-white focus:text-white focus:outline-none">
            <svg class="h-6 w-6 fill-current" viewBox="0 0 24 24">
              <path v-if="isOpen" fill-rule="evenodd" d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0 1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828 4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z"/>
              <path v-if="!isOpen" fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"/>
            </svg>
          </button>
        </div>
      </div>
      <nav :class="isOpen ? 'flex' : 'hidden'" class="">
        <ul class="flex w-full flex-col space-y-4">
            <li>
              <span class="text-white text-lg font-semibold leading-6 hover:text-[#6c63ff] cursor-pointer">Home</span>
            </li>
            <li>
              <router-link class="text-white text-lg font-semibold leading-6 hover:text-[#6c63ff]" :class="{'text-white': $route.path === '/about'}" to="/">Skills</router-link>
            </li>
            <li>
              <router-link class="text-white text-lg font-semibold leading-6 hover:text-[#6c63ff]" :class="{'text-white': $route.path === '/projects'}" to="/">Projects</router-link>
            </li>
            <li>
              <router-link class="text-white text-lg font-semibold leading-6 hover:text-[#6c63ff]" :class="{'text-white': $route.path === '/contact'}" to="/">Contact</router-link>
            </li>
          </ul>
      </nav>
    </header> 
  </template>
  
  <script>
  export default {
    data() {
      return {
        isOpen: false,
      }
    },
  }
  </script>
  <script setup>

  </script>

// src/components/Navbar/Navbar.tsx
import { useState } from "react";
import { Link } from "react-router-dom";

function Navbar () {
  const [isOpen, setIsOpen] = useState(false);

  const scrollStart = () => {
    document.getElementById("start")?.scrollIntoView({behavior: 'smooth'});
  }

  const scrollAbout = () => {
    document.getElementById("about")?.scrollIntoView({behavior: 'smooth'});
  }

  const scrollSkills = () => {
    document.getElementById("skills")?.scrollIntoView({behavior: 'smooth'});
  }

  const scrollWork = () => {
    document.getElementById("work")?.scrollIntoView({behavior: 'smooth'});
  }

  return (
    <nav className="flex items-center flex-wrap p-6 fixed bg-[#000000] text-white z-50 select-none">
      <div className="block ">
        <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center py-2 rounded text-black-500 hover:text-black-400"
        >
          <svg
          className={`fill-current h-5 w-5 ${isOpen ? "hidden" : "block"}`}
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
          >
            <path 
            d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" 
            />
          </svg>
          <svg
          className={`fill-current h-5 w-5 ${isOpen ? "block" : "hidden"}`}
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
          >
            <path 
            d="M10 8.586L2.929 1.515 1.515 2.929 8.586 
            10l-7.071 7.071 1.414 1.414L10 11.414l7.071 
            7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-1.414L10 
            8.586z" 
            />
          </svg>
        </button>
      </div>
      <div className={`w-full block ${isOpen ? "block" : "hidden"}`}>
        <div>
          <Link 
          to={"/"} 
          className="block pt-4 text-zinc-300 mr-4"
          onClick={scrollStart}
          >
            Start
          </Link>
          <a 
          className="block pt-4 text-zinc-300 mr-4 cursor-pointer "
          onClick={scrollAbout}
          >
            Über mich
          </a>
          <a 
          className="block pt-4 text-zinc-300 mr-4 cursor-pointer"
          onClick={scrollSkills}
          >
            Kompetenzen
          </a>
          <a 
          className="block pt-4 text-zinc-300 mr-4 cursor-pointer"
          onClick={scrollWork}
          >
            Portfolio
          </a>
        </div>
      </div>
    </nav>
  );
}
export default Navbar;
